### ISSUE TITLE
2022/03/13 19:14:18 No matches for videoUrlRegex: []

### ISSUE THREAD

**Issue by MaiSan9999** [BassMatt/TikiTokBot#8]
![image](https://user-images.githubusercontent.com/89659009/158075338-d8be2bed-dcf2-4cf0-b037-a236cdbfc357.png)

**Comment by silentsilas** [comment]
I'm also encountering this error. My guess is that Tiktok has changed their video URLs, or it now requires a header with a legit Tiktok session id. Haven't investigated further what it's returning in response.

Also think a failure to find a video shouldn't crash the bot.
